export type BlogMemoryEntry = {
  slug: string
  keyword: string
  intent: string
  createdAt: string
  status: "draft" | "published"
  notes?: string
}

export const blogMemory: BlogMemoryEntry[] = [
  {
    slug: "grabacion-eventos-madrid",
    keyword: "grabación de eventos madrid",
    intent: "comercial",
    createdAt: "2026-03-17",
    status: "published",
    notes: "URL /blog/grabacion-eventos-madrid reforzada y publicada el 2026-03-27 tras oportunidad en Search Console. Query principal: 88 impresiones, 0 clics, posición media 19.95. Sin canibalización para la query exacta; todo el volumen cae sobre esta URL.",
  },
  {
    slug: "video-corporativo-madrid",
    keyword: "video profesional para empresas madrid",
    intent: "comercial",
    createdAt: "2026-03-21",
    status: "published",
    notes: "Mejora de URL existente publicada el 2026-03-23 por oportunidad en Search Console. Query principal: 76 impresiones, 0 clics, posición media 28.62. Refuerzo SEO/comercial con propuesta, presupuesto, enlazado interno y CTA. No crear URL nueva para esta intención salvo cambio claro.",
  },
  {
    slug: "video-corporativo-madrid",
    keyword: "agencia de vídeo corporativo en madrid",
    intent: "comercial",
    createdAt: "2026-03-28",
    status: "published",
    notes: "Segunda mejora de la URL /video-corporativo-madrid publicada el 2026-03-28 tras oportunidad en Search Console. Query principal: 19 impresiones, 0 clics, posición media 25.11. La query cae casi entera sobre esta URL; se reforzaron H1, metadata, bloque comercial, presupuesto, FAQs, enlazado interno y CTA. No abrir URL nueva para esta intención salvo cambio claro sin canibalización.",
  },
  {
    slug: "video-corporativo-madrid",
    keyword: "productora de vídeos corporativos en madrid",
    intent: "comercial",
    createdAt: "2026-03-31",
    status: "published",
    notes: "Nueva mejora de la URL /video-corporativo-madrid publicada el 2026-03-31 tras oportunidad en Search Console. Query principal: 16 impresiones, 0 clics, posición media 24.94. La intención cae limpia sobre esta URL; se reforzaron metadata, copy comercial, FAQs, enlazado interno y CTA sin abrir una URL nueva ni generar canibalización evidente.",
  },
  {
    slug: "filmmaker-corporativo",
    keyword: "filmmaker corporativo",
    intent: "informacional",
    createdAt: "2026-05-05",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 4 impresiones, posición media 21.25. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "produccion-video-promocional-empresas-madrid",
    keyword: "producción de vídeo promocional para empresas en madrid",
    intent: "informacional",
    createdAt: "2026-05-06",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 7 impresiones, posición media 19.6. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "filmmaker-eventos",
    keyword: "filmmaker eventos",
    intent: "informacional",
    createdAt: "2026-05-07",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 4 impresiones, posición media 11.75. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "contenido-para-redes-sociales-madrid",
    keyword: "contenido para redes sociales madrid",
    intent: "informacional",
    createdAt: "2026-05-08",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 13 impresiones, posición media 31.4. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "video-vertical-profesional",
    keyword: "vídeo vertical profesional",
    intent: "informacional",
    createdAt: "2026-05-11",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 1 impresión, posición media 20. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "videos-profesionales-madrid",
    keyword: "videos profesionales en madrid",
    intent: "informacional",
    createdAt: "2026-05-12",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 24 impresiones, posición media 35.71. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "iluminacion-entrevistas-corporativas",
    keyword: "iluminación para entrevistas corporativas",
    intent: "informacional",
    createdAt: "2026-05-13",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "como-elegir-filmmaker-corporativo",
    keyword: "cómo elegir un filmmaker corporativo",
    intent: "informacional",
    createdAt: "2026-05-14",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "diferencias-video-institucional-video-de-marca",
    keyword: "diferencias entre vídeo institucional y vídeo de marca",
    intent: "informacional",
    createdAt: "2026-05-15",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "equipo-minimo-video-empresa",
    keyword: "equipo mínimo para grabar un vídeo de empresa",
    intent: "informacional",
    createdAt: "2026-05-18",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "briefing-video-corporativo",
    keyword: "briefing para tu vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-05-19",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "cuanto-cuesta-video-corporativo",
    keyword: "cuánto cuesta hacer un vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-05-20",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 1 impresión, posición media 76. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "realizador-video-corporativo-madrid",
    keyword: "realizador de vídeo corporativo madrid",
    intent: "informacional",
    createdAt: "2026-05-21",
    status: "published",
    notes: "Auto-generado por blog-auto. Search Console: 45 impresiones, posición media 36.16. Imágenes Unsplash/Pexels.",
  },
  {
    slug: "storyboard-video-corporativo",
    keyword: "storyboard para vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-05-22",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "musica-y-derechos-en-video-de-empresa",
    keyword: "música y derechos en vídeo de empresa",
    intent: "informacional",
    createdAt: "2026-05-25",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "produccion-eventos-corporativos-directo",
    keyword: "producción de eventos corporativos en directo",
    intent: "informacional",
    createdAt: "2026-05-26",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "video-recap-de-eventos",
    keyword: "vídeo recap de eventos",
    intent: "informacional",
    createdAt: "2026-05-27",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "sonido-directo-entrevistas",
    keyword: "sonido directo para entrevistas",
    intent: "informacional",
    createdAt: "2026-05-28",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "color-grading-video-corporativo",
    keyword: "color grading para vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-05-29",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "aspect-ratio-169-916-linkedin-instagram",
    keyword: "aspect ratio 16:9 vs 9:16 LinkedIn Instagram",
    intent: "informacional",
    createdAt: "2026-06-01",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "subtitulos-automaticos-video-corporativo",
    keyword: "subtítulos automáticos vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-06-02",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "como-preparar-un-ceo-para-grabar-a-camara",
    keyword: "cómo preparar a un CEO para grabar a cámara",
    intent: "informacional",
    createdAt: "2026-06-03",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "teleprompter-cuando-usarlo-y-cuando-no",
    keyword: "teleprompter cuándo usarlo",
    intent: "informacional",
    createdAt: "2026-06-04",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "locaciones-entrevistas-corporativas-madrid",
    keyword: "locaciones para grabar entrevistas corporativas en Madrid",
    intent: "informacional",
    createdAt: "2026-06-05",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "plazos-realistas-video-corporativo",
    keyword: "plazos realistas para entregar un vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-06-08",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "direccion-de-arte-video-corporativo",
    keyword: "dirección de arte para vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-06-09",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "branding-sonoro-video-empresa",
    keyword: "branding sonoro vídeo de empresa",
    intent: "informacional",
    createdAt: "2026-06-10",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "por-que-tu-video-corporativo-no-convierte",
    keyword: "por qué tu vídeo corporativo no convierte",
    intent: "informacional",
    createdAt: "2026-06-11",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "video-testimonial-vs-caso-de-estudio",
    keyword: "vídeo testimonial vs caso de estudio",
    intent: "informacional",
    createdAt: "2026-06-12",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "broll-video-corporativo",
    keyword: "b-roll para vídeo corporativo",
    intent: "informacional",
    createdAt: "2026-06-15",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
  {
    slug: "video-manifiesto-de-marca",
    keyword: "vídeo manifiesto de marca",
    intent: "informacional",
    createdAt: "2026-06-16",
    status: "published",
    notes: "Auto-generado por blog-auto (fallback evergreen, sin candidate SC limpio — token SC caducado). Imágenes Unsplash/Pexels.",
  },
]

export function findSimilarTopic(term: string) {
  const normalized = term.toLowerCase()
  return blogMemory.find((entry) =>
    normalized.includes(entry.keyword.toLowerCase()) || entry.keyword.toLowerCase().includes(normalized)
  )
}
